ALTER TABLE attachments
    ADD COLUMN IF NOT EXISTS hd_photo BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE attachment_upload_sessions
    ADD COLUMN IF NOT EXISTS hd_photo BOOLEAN NOT NULL DEFAULT FALSE;
