ALTER TABLE chat_members
    ADD COLUMN IF NOT EXISTS list_pinned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE chat_members
    ADD COLUMN IF NOT EXISTS list_pin_order INTEGER;

ALTER TABLE chat_folders
    ADD COLUMN IF NOT EXISTS included_chat_types VARCHAR(128),
    ADD COLUMN IF NOT EXISTS include_contacts BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_non_contacts BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_bots BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_read BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_unread BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_muted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_unmuted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_archived BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_non_archived BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS chat_folder_excluded_items (
    folder_id UUID NOT NULL REFERENCES chat_folders (id) ON DELETE CASCADE,
    chat_id UUID NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    PRIMARY KEY (folder_id, chat_id)
);
