ALTER TABLE polls
    ADD COLUMN IF NOT EXISTS quiz BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS correct_option_id UUID,
    ADD COLUMN IF NOT EXISTS explanation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS anonymous_votes BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS close_at TIMESTAMPTZ;
