ALTER TABLE call_sessions
    ADD COLUMN IF NOT EXISTS recording_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS recording_started_at TIMESTAMPTZ;

ALTER TABLE call_participants
    ADD COLUMN IF NOT EXISTS hand_raised BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS audio_muted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS muted_by_moderator BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS muted_by_user_id UUID REFERENCES users (id),
    ADD COLUMN IF NOT EXISTS muted_at TIMESTAMPTZ;

ALTER TABLE call_join_links
    ADD COLUMN IF NOT EXISTS mode VARCHAR(32) NOT NULL DEFAULT 'GROUP';
