spring:
  config:
    activate:
      on-profile: mvp

alex:
  features:
    stories: true
    bots: false
    calls: true
    secret-chats: false
    admin-compliance: true
    lawful-direct-export: false
    group-calls: true
    story-interactions: true
    bot-api-full: false
    business: false
    payments: false
    premium: false
    monetization: false
    translations: false
  notifications:
    expo:
      enabled: true
