spring:
  config:
    activate:
      on-profile: local
  flyway:
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

alex:
  auth:
    code:
      expose-debug-code: true
